# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qzeecontrol

# >> macros
# << macros

Summary:    QZeeControl - Control your smartphone remotely.
Version:    0.4.0
Release:    1
Group:      Amusements/Games
License:    GPLv3
URL:        http://qzeecontrol.garage.maemo.org/
Source0:    %{name}_%{version}.tar.gz
Source100:  qzeecontrol.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtConnectivity)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xtst)
BuildRequires:  desktop-file-utils

%description
QZeeControl lets you control your N9/N950 with a Zeemote(TM) Bluetooth remote control. QZeeControl is completly written from scratch in Qt/QML. Zeemote (TM) is a trademark of Zeemote Technology Inc. Other trademarks are property of their respective owners.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/QZeeControl_harmattan.desktop
/opt/QZeeControl
%{_datadir}/icons/hicolor/80x80/apps/QZeeControl80.png
# >> files
# << files
